### ISSUE TITLE
port-forwarding instructions for v06

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1041]
I *think* this command: `kubectl port-forward svc/ambassador -n kubeflow 8080:80` (from https://www.kubeflow.org/docs/other-guides/accessing-uis/) needs to be `kubectl port-forward svc/ambassador -n istio-system 8080:80` for 0.6
(but namespace needs to stay as is for earlier versions)

**Comment by sarahmaddox** [comment]
/assign

I'm updating the screenshot and UI text references on this page. I'll take this one on too.

**Comment by jlewi** [comment]
Reopening this because port-forwarding to Ambassador is not the right thing to do.
The correct thing to do see kubeflow/kubeflow#3618 is to port-forward to the istio gateway

```
kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80
```

We no longer install Ambassador except in the basic auth case. port-forwarding isn't guaranteed to work in the event user sets up Auth.

If users want to do port-forwarding they should follow the instructions to setup on an existing cluster and not install Dex or anything else.

I'll send a PR to update the instructions.


see also #1023

**Comment by amygdala** [comment]
yeah, I just belatedly realized this today too.  If you're putting in a PR to change it I'll hold off.

**Comment by jlewi** [comment]
Thanks @amygdala #1067 should just have been merged.
