### ISSUE TITLE
[Developer Docs] Explain rebasing vs. merging 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1094]
A lot of contributors run into problems because they try to pull in the latest changes on master by doing a merge.

This leads to problems because when they create a PR they end up trying to recommit changes that were already merged onto master.

It manifests in the PR by a commit history showing a lot of changes unrelated that have already been committed.

Instead contributors should do a rebase.

Here's a good tutorial for rebasing 
https://www.atlassian.com/git/tutorials/merging-vs-rebasing

The natural flow to rebase a change is something like this

```
git fetch origin
git rebase -i origin/master
```
  * This assumes the remote fork of the Kubeflow repository is named origin
  * Fetch pulls in the latest commits to the origin
  * rebase -i will interactively try to apply the commits on your branch to the tip of origin/master
     * This means you can choose which commits to pick, drop or squash

We should create a page that describes this workflow so we can point contributors at it.

**Comment by sarahmaddox** [comment]
Thanks @jlewi! Just a note that we host our developer-focused docs in the GitHub repo (https://github.com/kubeflow/kubeflow) rather than on the website. Suggestion: We should either place this doc in the [docs_dev](https://github.com/kubeflow/kubeflow/tree/master/docs_dev) directory in that repo, or create a more general developer-docs directory in the same repo.

**Comment by jlewi** [comment]
@sarahmaddox Could we add this information to the contributing guide>
https://www.kubeflow.org/docs/about/contributing/#owners-files-and-pr-workflow

We already have a section there on the PR workflow.

Leaving aside for now whether it makes sense to split the developer docs into two locations right now there is a reasonable difference between the docs on the website and the docs_dev.

The docs on the website are aimed at first time contributors.

The docs in docs_dev (e.g. instructions for doing releases) are for maintainers.

**Comment by sarahmaddox** [comment]
Hmm. I'm uncomfortable about documenting something as complex as git rebasing on our website. The docs in the contributor's guide (https://www.kubeflow.org/docs/about/contributing/#owners-files-and-pr-workflow) talk about Kubeflow-specific dev workflow (owners files, bots, review process) rather than generic git skills. 

If we add git-related guides to the above page, it will become very long. We'll want to split it. And then we'll want to add more dev guides - it seems weird to jump directly into rebasing without giving a bit more of an intro to git...

Instead, how about adding the hint about rebasing in a README here:
https://github.com/kubeflow/kubeflow/tree/master/docs_dev
or even here:
https://github.com/kubeflow/kubeflow

The README could then also include a high-level first-time contributor's guide, similar to what we already have in the docs repo for docs contributors:
https://github.com/kubeflow/website/blob/master/README.md

**Comment by jlewi** [comment]
Good point; lets just put it in docs_dev for now.
I'm not that worried about the location; I just want something I can link to on PRs

**Comment by sarahmaddox** [comment]
I'm closing this issue, as it's not one we'll tackle in the website docs.
/close
