### ISSUE TITLE
Test and fix the guide to Microk8s/Multipass for Kubeflow installation

### ISSUE THREAD

**Issue by shouryaotta** [kubeflow/website#1113]
I need to use the latest mlpipelines released in 0.6.2 and am using a desktop to try it out. I have installed microk8s using the instructions at 
`https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/`

I used the latest executable for 0.6.2 with the following instructions. 

```bash
# The following command is optional, to make kfctl binary easier to use.
export PATH=$PATH:<path to kfctl in your kubeflow installation>

# Initialize a kubeflow app:
export KFAPP=<your choice of application directory name> (ensure this is lowercase)
kfctl init ${KFAPP}

# Generate and deploy the app:
cd ${KFAPP}
kfctl generate all -V
kfctl apply k8s -V

```
I get the following error message : 

```
INFO[0039] creating ClusterRoleBinding/ml-pipeline-scheduledworkflow  filename="kustomize/kustomize.go:447"
INFO[0039] creating Deployment/ml-pipeline-scheduledworkflow  filename="kustomize/kustomize.go:447"
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create default profile from &{{Profile kubeflow.org/v1alpha1} {kubeflow-anonymous      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{User  anonymous }} { }} Error: no matches for kind "Profile" in version "kubeflow.org/v1alpha1"

Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for apply
  -V, --verbose   verbose output default is false

couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create default profile from &{{Profile kubeflow.org/v1alpha1} {kubeflow-anonymous      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{User  anonymous }} { }} Error: no matches for kind "Profile" in version "kubeflow.org/v1alpha1"

```

Earlier the templates were using argoproj.io. Does something else need to be updated for the new profile to work ?

**Comment by sarahmaddox** [comment]
See further info in the following two issues:
* https://github.com/kubeflow/website/issues/1163
* https://github.com/kubeflow/website/issues/1187

I'll close those issues and we'll track the work on this issue, since it's the first one raised.

**Comment by sarahmaddox** [comment]
@ammarn911 is tackling this issue

**Comment by sarahmaddox** [comment]
Status: PR https://github.com/kubeflow/website/pull/1469 has added an **alpha** banner to the Microk8s installation doc. There are still some questions to resolve - see comments in the PR, so I'll leave this issue open.

**Comment by kbhawkey** [comment]
A couple of thoughts about deploying kubeflow on workstations/appliances:

There are a number of places in the kubeflow docs that start to outline how to deploy kubeflow in a single node cluster (and workstation/appliance) and finish in another set of instructions. This can be confusing.

I tried to install kubeflow on a microk8s cluster and Ubuntu; I followed the instructions from https://master.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/.

On this page, it may help to clarify the version of kubeflow that is available to install (and what components are in that package). Or, can you specify the version by a channel flag?
I installed Kubernetes 1.15 instead of 1.17 (by way of the channel flag).

How is Ambassador deployed or needed (routing)? Is there an explanation about Ambassador in the kubeflow docs?

During a second microk8s+kubeflow installation/deployment, I used the kubeflow manifests (kfctl_k8s_istio.0.7.1.yaml) and deployed into microk8s. The deployment was successful, though, my cluster became unresponsive and I had difficulty removing kubeflow from the cluster. I read through the following pages:
https://master.kubeflow.org/docs/other-guides/kustomize/
https://master.kubeflow.org/docs/started/getting-started/

I would be interested in deploying a smaller set of kubeflow components that support a couple of samples/demos (deploy the examples with the prerequisite components).

**Comment by sarahmaddox** [comment]
Thanks @kbhawkey that's super useful feedback.

/cc @jlewi 
/cc @ammarn911

**Comment by jlewi** [comment]
@ammarn911 I think we discussed this at the community meeting. I think you said you have testing in place? 

The other Canonical engineer mentioned that there is testing in this repo
https://github.com/juju-solutions/bundle-kubeflow/

Is that covering the current installation guide

I think the updated docs are now visible here
https://master.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/

What is the follow on work to #1469?

**Comment by jlewi** [comment]
See https://github.com/kubeflow/website/pull/1609#issuecomment-583255010

Do we need to add that to the instructions?

Also it looks like there is a reference to Ambassador in the guide 
https://github.com/kubeflow/website/blob/master/content/docs/other-guides/virtual-dev/getting-started-multipass.md#2-enable-kubeflow

That needs to be updated.

/cc @knkski

**Comment by jlewi** [comment]
Has this been fixed can we close it?

**Comment by sarahmaddox** [comment]
I think the Microk8s/Multipass doc still needs some work. For example, it still refers to Ambassador:
https://www.kubeflow.org/docs/started/workstation/getting-started-multipass/
