### ISSUE TITLE
Getting started with Minikube script is outdated

### ISSUE THREAD

**Issue by muscovitebob** [kubeflow/website#1183]
[This page](https://github.com/kubeflow/website/blob/master/content/docs/other-guides/virtual-dev/getting-started-minikube.md) describes quick setup using a script located [here](https://raw.githubusercontent.com/kubeflow/kubeflow/master/scripts/setup-minikube.sh). However, this appears to assume an installation process that is outdated and has been removed in [this commit](https://github.com/kubeflow/kubeflow/pull/4084). Hence the setup script fails when it attempts to download & run the nonexistent files:

`./download.sh: line 1: 404:: command not found
./setup-minikube.sh: line 196: ./scripts/kfctl.sh: No such file or directory
~/Documents/kubeflowTest ~/Documents/kubeflowTest
./setup-minikube.sh: line 198: cd: localapp: No such file or directory
./setup-minikube.sh: line 199: ../scripts/kfctl.sh: No such file or directory
./setup-minikube.sh: line 200: ../scripts/kfctl.sh: No such file or directory
~/Documents/kubeflowTest
`

The commit references a go program but it is unclear where this can be found or how to run it.

**Comment by muscovitebob** [comment]
I see that there appears to be a major refactoring going on with the whole process being handled by a [new tool](https://github.com/kubeflow/kfctl), which I did not see before.

**Comment by sarahmaddox** [comment]
PR https://github.com/kubeflow/website/pull/1325 deletes the script section from the page. Since the script section was intended as a quick installation option, this solves this particular issue.

Still to be determined is how well the full installation of mini-kube works.

I'll close this issue for now, as the particular point it raises has been addressed. Thanks for reporting it and thanks to the fixer too.

/close
