### ISSUE TITLE
Document that Kubeflow 0.7 doesn't work with K8s 1.16 and has only been tested on 1.14

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1272]
See kubeflow/manifests#375

We know that Kubeflow doesn't work with Kubernetes 1.16.
We haven't tested Kubeflow on Kubernetes 1.15 so we don't really know.
We test Kubeflow on GKE with 1.14.

We should document this on the docs and point to it.

I might suggest creating a page with some sort of compatibility matrix.

We have other versioning that we want to document; e.g. ISTIO version; knative version and KFServing.

I think we want to distinguish between

* What we test/support
* What we know doesn't work
* What we haven't tested (maybe this can be specified implicitly by not listing it).

@sarahmaddox Any suggestions on the structure location of this information?

P0 because I think we want to call out that 1.16 is known not to work with 0.7 and 1.14 is what we test as part of the release.
/cc @animeshsingh

**Comment by sarahmaddox** [comment]
Thanks @jlewi 

I think we should tackle this in 2 stages.

First, let's get the K8s requirements sorted out. 

* We currently list the minimum K8s version here: https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements
* We should add the info about the tested version and the incompatible version to the same bullet point in the above page. We should use shortcodes to contain the K8s version number, to free us up to use it in many places if necessary. (A shortcode also makes [searching](https://github.com/kubeflow/website/search?q=kubernetes-min-version&unscoped_q=kubernetes-min-version) easy.) The shortcode should be similar to the one we use for min version: https://github.com/kubeflow/website/blob/master/layouts/shortcodes/kubernetes-min-version.html
* We used to include the K8s requirements on [the getting-started overview page](https://www.kubeflow.org/docs/started/getting-started/), but the requirement was removed from that page because people felt it was only applicable to the existing-k8s guides. I think we should put it back on the page, as it's super relevant for a Kubeflow deployment.

Second, when we've gathered all the info for a compatibility matrix that includes Istio, KFServing, etc, then we should create a new issue (not a P0) for that doc. I think it should go in this section:
https://www.kubeflow.org/docs/other-guides/

What do folks think of the above proposals?

**Comment by sarahmaddox** [comment]
I've created issue https://github.com/kubeflow/website/issues/1281 to gather information about the version matrix and track the creation of the doc.

Let's use this current issue to track the K8s version requirements since that's the P0 for v0.7.
