### ISSUE TITLE
Should we have a developer section?

### ISSUE THREAD

**Issue by lluunn** [kubeflow/website#148]
We can move some information from https://github.com/kubeflow/testing/blob/master/README.md.

E.g. e2e test structure, how to debug and get logs

cc @abhi-g

**Comment by abhi-g** [comment]
Good idea.

abhishek

**Comment by sarahmaddox** [comment]
Another option is to put the Kubeflow-developer docs into the wiki at kubeflow/kubeflow. (The wiki isn't currently enabled, but we can enable it.)

I'm a little concerned that people may become confused if we add the developer docs to the website. A large part of our audience is developers (though they're not necessarily Kubeflow contributors) and if they see a "developer's guide" they will think it's for them.

What do folks think of using the wiki for the developer docs - that is, the docs for developers who contribute to the Kubeflow code?

**Comment by sarahmaddox** [comment]
My 2c is that the developer docs are better located in the code base rather than on the website. Most people will expect them there, and it may be confusing to have the developer docs on the website along with the docs for users of Kubeflow. I'm closing this issue as answered, but please do re-open it if you think we should work on it.

/close
