### ISSUE TITLE
Unable to run example code in "Experiment with your notebook" section

### ISSUE THREAD

**Issue by avizmil** [kubeflow/website#1507]
I followed all steps but when I run the example code I get:
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f591bfcf84f5> in <module>
----> 1 from tensorflow.examples.tutorials.mnist import input_data
      2 mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
      3 
      4 import tensorflow as tf
      5 

ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'
`

what am I missing?

**Comment by sarahmaddox** [comment]
This needs investigation. The doc is here:
https://www.kubeflow.org/docs/notebooks/setup/#experiment-with-your-notebook

**Comment by jbottum** [comment]
@avizmil I have triaged the issue, which hopefully will provide an owner.   Note - I have not used this example, but sometimes the owner of the data moves it to another directory.

**Comment by JohanWork** [comment]
@avizmil I just tested the tutorial and works fine to me. There are some warnings but it do run and give the  Accuracy:  0.9018. Could it be the version of tensorflow?

**Comment by sarahmaddox** [comment]
Thanks @avizmil and @JohanWork I've also just run the example code successfully on a Kubeflow 1.0 installation.

I used the following image when setting up my notebook server in Kubeflow: `tensorflow-1.15.2-notebook-cpu:1.0.0`.

I see that one thing has changed since the doc was written: There is no longer a default image selected. You have to choose an image. The doc still assumes that the default image is a TensorFlow one, and the doc doesn't give advice on which image to choose in order to run the test. I'll update the doc to give that advice.

Is it possible that your notebook server is running something other than TensorFlow?

**Comment by karanveersingh5623** [comment]
I am still facing the issue to run the sample code , no module named 'tensorflow.examples' 
How and where I should copy examples folder to tensorflow python3 site-pacakages ?

**Comment by yankunsam** [comment]
the same for me, which images should I select? 
![image](https://user-images.githubusercontent.com/16130147/133349504-215a10de-3928-4623-8b64-ce2d96be7967.png)
