### ISSUE TITLE
Offline book format (Kindle/EPUB/PDF) for website

### ISSUE THREAD

**Issue by cloudbow** [kubeflow/website#1593]
There needs to be a kindle book avaialable for this documentation as its too tedious to read this for a offline reference

**Comment by sarahmaddox** [comment]
@cloudbow That's an interesting idea. A Kindle format (mobi), or EPUB, PDF,  or some other offline format would be a very nice feature to add to the website. I'd like to see an option for users to generate and download the content at the time they need it (rather than the documentation maintainers needing to generate and maintain a static copy of the docs).

I think the generated file needs to:

* Include the date of generation and the Kubeflow version information on every page, so that people know how up-to-date the generated file is.
* Comply with the [CC BY 4.0 licence](https://creativecommons.org/licenses/by/4.0/), as the Kubeflow doc is distributed under that licence.

@theadactyl @abhi-g @jbottum Do you have any thoughts here? This could be a nice doc sprint project.

**Comment by jbottum** [comment]
@sarahmaddox I think this request is interesting.   I have a few questions - how much time will it take to convert the format and scrub the results into something that can be published?  Is this a low, medium or high work effort ?   Will get easier for the next release?  and how many people will use it ?   and how will they use it i.e. for offline reading and/or as a guide in configuration, debugging ?

**Comment by jtfogarty** [comment]
\priority p2
