### ISSUE TITLE
Tech writer revisions needed - Pipelines standalone installation

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/website#1622]
Page: [KFP standalone installation guide](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/)

Here are a few issues that I noticed while reviewing this page. It may benefit from additional polish as well.
- Brand name usage and terminology:
  - github should be GitHub
  - repo should be repository
- [Deploying KFP from scratch](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines-standalone-from-scratch) includes urls in the text. Replace the URL in the text with an appropriate clickable description of the link.
- [Deploy on GCP with CloudSQL](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#deploy-on-gcp-with-cloudsql-and-google-cloud-storage) needs a better description to help users understand if this case applies to them.
- [Disable the public endpoint](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#disable-the-public-endpoint), instructions would be helpful for commenting out the "proxy component"
- [Maintain a repo for your manifests](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#maintain-a-repo-for-your-manifests), a better explanation of where to find the YAML file would be helpful.
- [How to deploy using the repo](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#how-to-deploy-upgrade-and-uninstall-using-the-repo)
  - Please define the $YOUR_REPO variable. Is it meant to link to a repository or to a YAML file in a repository? Does this approach assume that the repository is publicly accessible?
  - The Markdown for the "Check Kubeflow Pipelines github repo" is broken.

**Comment by sarahmaddox** [comment]
@joeliedtke Let's discuss the following two points (in this issue and similar issues):

> kustomize should be Kustomize
> kubectl refers to a command, it should be in code font, unless it is part of a link

Currently the docs use kustomize with lower case (unless at the start of the sentence) because the kustomize docs follow that pattern. I think the brand is with a lower case.

The docs also use kfctl in plain text rather than code font, unless part of a code snippet. kfctl is actually the name of the binary/tool, as well as the command itself. Previously, the Kubernetes docs followed the same pattern when referring to kubectl. I've just had a look at the Kubernetes docs, and they've switched to using code font for kftcl in almost all (but not entirely all) cases. How would you feel about keeping kfctl in plain text throughout the Kubeflow docs, unless part of a code snippet?

**Comment by joeliedtke** [comment]
Interesting, Kustomize is upper-case on Kustomize.io and lowercase in the docs. I think it is fair for the docs usage to win in this case.

Do you think that it would be confusing for users if Kubeflow styles kfctl and kubectl differently? It seems like that may be the case. 

I'll remove the tasks to update Kustomize and kubectl usage.

**Comment by sarahmaddox** [comment]
@kbhawkey If you add a comment to this issue, I'll be able to assign it to you.

**Comment by kbhawkey** [comment]
Hello @sarahmaddox ,
Yes, it is okay to assign me to this issue, though, if someone else needs to jump
in that is fine too!

**Comment by sarahmaddox** [comment]
Thanks @kbhawkey I'll assign it to you, since you're already working on a PR. No pressure to get this done quickly!

/assign @kbhawkey

**Comment by sarahmaddox** [comment]
This is done.
/close
