### ISSUE TITLE
Remove the Minikube installation guide

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1662]
Based on recent testing, discussions, and bug reports, we think that the deployment of Kubeflow on Minikube is no longer feasible.

One example: Thanks to @daniel-bejarano for reporting the issues they encountered:
https://github.com/kubeflow/website/issues/1660

We should therefore remove this page, and fix any links that point to it from within the docs, and add a redirect to catch incoming links:
https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/

**Comment by sarahmaddox** [comment]
Another example of issues encountered with Kubeflow on Minikube: Thank you to @dkurt for the thorough testing! https://github.com/kubeflow/website/pull/1609

**Comment by wdhorton** [comment]
@sarahmaddox is there any plan to bring back Minikube support in the future? I'm trying to understand if it was some fundamental incompatibility or just too many bugs and errors to be supported right now.

**Comment by sarahmaddox** [comment]
@wdhorton I think the issues stem from the resources that Kubeflow requires, which make it infeasible to run Kubeflow on Minikube on a desktop/laptop at this point. @abhi-g can probably give more details.

**Comment by abhi-g** [comment]
@wdhorton As Sarah mentions, generally installing various Kubeflow components end up consuming enough CPU resources that locally on the laptops its unusable with minikube. Also, I have been unable to get Istio setup working in Minikube. Given that we are not maintaining the minikube setup, we can't recommend it to users anymore. On single machine there are a few other options: microk8s, miniKF, and I saw one of the blogs suggesting using docker with K8s APIs.

**Comment by javajon** [comment]
Kubernetes flourishes because of its portability. Kubeflow benefits from this as well as stated on the [front page](https://www.kubeflow.org/docs/about/kubeflow/), it reads
> Anywhere you are running Kubernetes, you should be able to run Kubeflow.

With the removal of Minikube, the words _anywhere_ and _should_ becomes misleading. On the [Minimum system requirements page](https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements) it states:
> 4 CPU
> 50 GB storage
> 12 GB memory

With some default overriding, these documented requirements can be reserved to a Minikube VM (supported by the underlying turtles like the VM (e.g. VirtualBox) and the laptop os/hardware.)

Granted it's larger than the default requirement for the Minikube, but folks involved in ML understand the benefits of large enough laptops. Switches like --cpus, --memory, and --disk-size can provision Minikube beyond the defaults. Also, yes as time goes on for a first-time learner, running more realistic workflows should be moved to larger compute resources but the point of Minikube is to get started.  

The testing matrix for all the Kubernetes targets combined with Kubeflow resource requests makes testing operators like Kubeflow much more difficult so it's understandable why Minkube is one mole to whack. Perhaps, Kubeflow has a "light" deployment for learners, but the would also add to the testing complexities.

This Minikube exclusion _may_ be excluding an important population of first-time learners.

**Comment by sarahmaddox** [comment]
Thanks @javajon for this feedback. I have a request. :)  Would you be able to put together a guide for deploying Kubeflow on Minikube and running a simple task to verify that the deployment is working? If you have bandwidth to do this, I'll open a new issue to track the work.

The guide would go into this section:
https://www.kubeflow.org/docs/started/workstation/
Here's the source on GitHub:
https://github.com/kubeflow/website/tree/master/content/docs/started/workstation

(We need to reorganize those docs, and rename the section to refer to single-node installations, as described in the [installation overview](https://www.kubeflow.org/docs/started/getting-started/#single-node) but that's another task.)

Here's a guide to updating the docs:
https://github.com/kubeflow/website/blob/master/README.md

**Comment by janeman98** [comment]
@sarahmaddox  @javajon 
I can write a tutorial starting from installing minikube and Kubeflow, compiling a pipeline example, uploading the complied application to Pipeeline UI, and  executing the uploaded application. Will that help?

**Comment by abhi-g** [comment]
That would be great. Please try out the mnist example once you have
Kubeflow deployed to ensure everything is functional.

**Comment by jodavis-suse** [comment]
After-the-fact-feedback: I came back to my notes on the minikube (k8s 1.14) & kubeflow deployment I did just 11 days ago and now find the directions I followed are no longer posted online.  Pretty frustrating.

**Comment by janeman98** [comment]
@sarahmaddox 
I have finished the initial draft in [PR1743](https://github.com/kubeflow/website/pull/1743)  - which cover installation of minikube (+ other components) + kubeflow, setting up dev env, compilation of a pipeline sample (sequential.py), upload of compiled application to Kubeflow UI, and execution of the uploaded application.  Questions:
1. do we need to add doc-sprint tag to PR1743?
2. the tutorial is e2e, not sure https://www.kubeflow.org/docs/started/workstation/ is a good location. If not, where is the best location?
3. do I need to remove the prefix "WIP" to get your review feedback?

@abhi-g 
I have not tried out MNIST example, but sequential.py work fine. Will add MNIST after I test it. It seems a lot of people are waiting for minikube instruction, just want to put the initial version out first.

**Comment by janeman98** [comment]
@abhi-g 
[MNIST example ](https://github.com/kubeflow/examples/tree/master/pipelines/mnist-pipelines) is NOT working properly. I get the same ksonnet-related segfault error in the serve step as reported in [issue 1611](https://github.com/kubeflow/website/issues/1611).  It maybe better to have a non-ksonnet implementation.

**Comment by sarahmaddox** [comment]
@janeman98 Thanks for your work on this so far!

You are right that the MNIST Pipelines example is not working. See issues https://github.com/kubeflow/examples/issues/727 and https://github.com/kubeflow/website/issues/1611 (which you already mentioned). We need to find a different example to test the deployment.

I've created a new issue https://github.com/kubeflow/website/issues/1751 to track ongoing work. Let's move the discussion to that issue, since this issue # 1662 is closed.

I've answered your other questions on PR https://github.com/kubeflow/website/pull/1743
