### ISSUE TITLE
But what is a pipeline version? 

### ISSUE THREAD

**Issue by tall-josh** [kubeflow/website#1833]
I've read the [sdk-overview](https://www.kubeflow.org/docs/pipelines/sdk/sdk-overview/) and [Using the SDK to create a pipeline and a pipeline version ](https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/) but I am still none-the-wiser regarding what pipeline version is. The name suggests its iterative changes on an existing pipeline. But what is a `pipeline version yaml` where do I learn about it and how to use it?

**Comment by joeliedtke** [comment]
/assign

In Kubeflow Pipelines 0.2.5 and higher, you can add a new version of a pipeline rather than creating a completely new pipeline record for each version. Here is an example that [uses the SDK to create a pipeline and then add a new version of that pipeline](https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/#creating-a-pipeline-and-a-pipeline-version-using-the-sdk).
