### ISSUE TITLE
Hard to find community resources

### ISSUE THREAD

**Issue by ewilderj** [kubeflow/website#185]
I noticed a flattening in the number of people joining the Kubeflow mailing list, so I went to the web site to see how discoverable it was. What I found is that apart from directions to join the Github org, I couldn't easily find directions to either the mailing list, or the Slack channel. Anywhere "community" is mentioned, these resources ought to be reachable, and also they ought to be reachable from the front page too.

**Comment by tlkh** [comment]
Hi @ewilderj, I’m wondering if the Slack channel should be open to all. Currently, it seems like only emails from a few whitelisted domains (eg google.com) are allowed to register.

**Comment by ewilderj** [comment]
@tlkh it depends on which link is given, there's a link which enables anyone to get in... but a bare "kubeflow.slack.com" will go to the whitelisted page, for sure.

**Comment by ewilderj** [comment]
This link will work as an  open invitation: https://join.slack.com/t/kubeflow/shared_invite/enQtMjgyMzMxNDgyMTQ5LWUwMTIxNmZlZTk2NGU0MmFiNDE4YWJiMzFiOGNkZGZjZmRlNTExNmUwMmQ2NzMwYzk5YzQxOWQyODBlZGY2OTg

**Comment by ewilderj** [comment]
Here's some of the community content that would be good to reflect on the web site:
https://github.com/kubeflow/community/blob/master/README.md

**Comment by sarahmaddox** [comment]
I'll take this on. Here are some suggestions for discussion:

* On the [front page](https://master.kubeflow.org/), there's a "Community" section right at the bottom. I propose to add a "Contribute" button at the top too, next to the existing "Get Started" button, pointing to the [contributing page in the docs](https://master.kubeflow.org/docs/about/contributing/):
![image](https://user-images.githubusercontent.com/6138251/44972026-144a3780-af9b-11e8-84f7-20b270f82738.png)

* Add a prominent link on the existing [contributing page in the docs](https://master.kubeflow.org/docs/about/contributing/), pointing to the [community page in the docs](https://master.kubeflow.org/docs/about/community/).

* Expand the info on the  existing [community page in the docs](https://master.kubeflow.org/docs/about/community/), and check it has everything that's in the [GitHub community README](https://github.com/kubeflow/community/blob/master/README.md).

* Minimise the info in the [GitHub community README](https://github.com/kubeflow/community/blob/master/README.md) so that it welcomes people and points them to the docs for info. (Otherwise we'll find ourselves being inconsistent between the docs and the README.)

* Also add more about contributing to the docs.

How does that sound?
