### ISSUE TITLE
Component Specification: How to produce output by value with a reusable component?

### ISSUE THREAD

**Issue by tholop** [kubeflow/website#1900]
The documentation page about [Component Specification](https://www.kubeflow.org/docs/pipelines/reference/component-spec/) shows in particular how to:
- consume inputs by value
- consume inputs by file
- produce outputs by file

This page does not explain how to produce outputs by value (i.e. `outputValue` placeholder) when creating a reusable component from a Yaml specification. The [data passing tutorial](https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/Data%20passing%20in%20python%20components.ipynb) shows how to do so, but only for lightweight Python components.

I think that the documentation could be improved by adding an example of usage of `ouputValue` for reusable components, and I would be interested too!

**Comment by sarahmaddox** [comment]
@Ark-kun Do you have any examples handy? :)
/cc @joeliedtke

**Comment by Ark-kun** [comment]
Thank you for your interest in reusable components and the lighweight components feature.

`outputValue` does not exist in the ComponentSpec schema or in any other place in the SDK.

The standard interface of a command-line program does not really provide a way to do that in a universal way. The only data that the program kind of outputs is the contents of `STDOUT`and `STDERR`, but usually this is not used for outputting data values.

So, the only common way to get some output data from a command-line program is to give it an `outputPath` so that the program can write the data there.

The lightweight python components feature just builds on top of the ComponentSpec (reusable components) and injects code to serialize small data values and write them to files. See the generated code:
https://github.com/kubeflow/pipelines/blob/56d519e9f76c57bdffc593742e23b790a0505310/components/gcp/automl/create_model_for_tables/component.yaml#L99

So, if you are creating a component from a command-line program, just use `outputPath` and write that data pieces to the provided paths. This tutorial may come handy: https://github.com/Ark-kun/kfp_samples/blob/master/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs/106%20-%20Creating%20components%20from%20command-line%20programs.ipynb

P.S. When you create a lightweight component, you can write it to a file for sharing and inspecting. It's a proper reusable component.yaml. `func_to_container_op(my_func, output_component_file='my.component.yaml')` . This will demystify the lightweight components for you.

**Comment by tholop** [comment]
Thank you for the detailed answer, it makes more sense now.

I'll just use `outputPath`. I was a bit confused by the UI, which makes a clear distinction between `Output parameters` and `Output artifacts`.

Thanks again.


![Screenshot](https://user-images.githubusercontent.com/32133147/79578351-1be92200-8094-11ea-822e-5410322bc103.png)

**Comment by sarahmaddox** [comment]
Thanks @Ark-kun and @tholop! I'm going to close this issue as answered. If there's still doc work to do, please do re-open the issue and/or send a PR. :)

/close
