### ISSUE TITLE
Installing kubeflow without istio

### ISSUE THREAD

**Issue by jagadeeshi2i** [kubeflow/website#2116]
I've tried installing kubeflow without istio. I used following the link: https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ and ran into this error: `TLS match must have at least one SNI host`. Using `kfctl_aws.yaml` from manifests in AWS EKS. My requirement is to run KFserving with Kubeflow.

**Comment by 8bitmp3** [comment]
Hi @Jeffwan @PatrickXYS can you please help if you can? @jagadeeshi2i used "`kfctl_aws.yaml` from manifests in AWS EKS". Thanks!

/assign @Jeffwan @PatrickXYS 
(from the `docs/aws` `OWNERS` file)

**Comment by PatrickXYS** [comment]
1. It would be great to use stable version of manifest, such as [kfctl_aws_v1.1.0](https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_aws.v1.1.0.yaml).

2. If you don't want to use istio, you need to do some customization in the manifest file, because without istio, some features will be disabled, including ingress, kubeflow central dashboard, etc.

**Comment by jagadeeshi2i** [comment]
Tried installing kfctl_aws_v1.1.0.yaml. The installation did not start throwing the error.

**Comment by Jeffwan** [comment]
@jagadeeshi2i Did you upgrade your `kfctl` to 1.1.0?  Seems your input type in kfctl_aws.yaml doesn't work with kfctl aws plugin. I would suggest you to do an upgrade
