### ISSUE TITLE
[Testing] Standardize markdown linting rules

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/website#2381]
In general, I did some quick research, it seems the extra rules like "always adding empty lines before and after code blocks" are not implemented by markdown formatters. However, they can be enforced by linters like https://github.com/DavidAnson/vscode-markdownlint#configure. Install that plugin on your vscode and it automatically highlights problems. Additionally, we could set up the same process in presubmit tests, so it's automatically checked for everyone. I think that's a much better way to get everyone writing markdowns with the same set of best practices. It should also save all the manual review efforts we spend on these.

_Originally posted by @Bobgy in https://github.com/kubeflow/website/pull/2372#discussion_r533124536_

**Comment by Bobgy** [comment]
/cc @joeliedtke @8bitmp3 
I feel like this is the best way to align on best practices with minimum ongoing cost.
What do you think?

**Comment by 8bitmp3** [comment]
Thanks @Bobgy that's a good idea IMO 👍 

Perhaps to make things easy we can also explore adding a linter to CI that test `.md` files and highlights things to PR authors. For example, there's https://github.com/markdownlint/markdownlint and https://github.com/marketplace/actions/markdownlint-cli

VS Code has some good extensions - I'm not 100% sure all contributors would be using it 🤔.

I'd also highly recommend adding a link checker to CI - some PRs may cause 404 errors on other pages (e.g. `kfserving` very recently).

**Comment by 8bitmp3** [comment]
From https://github.com/kubeflow/website/pull/2372#issuecomment-735987955 
> If we move forward on this, I would recommend that we approach this like building a linter for Markdown docs. It would also be great to also include a check for terms that should not be used in docs (such as "please"). I have started to look into building a linter in the past, but I haven't had much time to devote to it.   

@joeliedtke I think that's a great idea 👍 

At TensorFlow, @lamberta and team built the `nblint` tool for notebooks that you may be aware of (https://github.com/tensorflow/docs/tree/master/tools/tensorflow_docs/tools). Here's a Google `style` guide example: https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/tools/nblint/style/google.py

**Comment by Bobgy** [comment]
> Thanks @Bobgy that's a good idea IMO 👍
> 
> Perhaps to make things easy we can also explore adding a linter to CI that test `.md` files and highlights things to PR authors. For example, there's https://github.com/markdownlint/markdownlint and https://github.com/marketplace/actions/markdownlint-cli
> 
> VS Code has some good extensions - I'm not 100% sure all contributors would be using it 🤔.
> 
> I'd also highly recommend adding a link checker to CI - some PRs may cause 404 errors on other pages (e.g. `kfserving` very recently).

Totally agree, https://github.com/DavidAnson/markdownlint is a nodejs tool that powers the vscode plugin I mentioned in the issue. I believe adding it to CI will be very beneficial for guarding new changes.

Although, to achieve the best contribution experience, I'd suggest any contributors to install the plugin, so that they can get instant feedback right in the editor, when they write the documentation.

**Comment by Bobgy** [comment]
> I'd also highly recommend adding a link checker to CI

Is there any existing tools that can do this? That will be very beneficial

**Comment by 8bitmp3** [comment]
> > I'd also highly recommend adding a link checker to CI
> Is there any existing tools that can do this? That will be very beneficial

@Bobgy I found five Markdown-specific link checkers on GH Actions: https://github.com/marketplace?type=actions&query=markdown+link
including this one: https://github.com/marketplace/actions/markdown-link-check

---

> Although, to achieve the best contribution experience, I'd suggest any contributors to install the plugin, so that they can get instant feedback right in the editor, when they write the documentation.

I agree but I'm not 100% sure everyone wants to use VS Code as an IDE. Some folks may be editing Markdown using PyCharm, Atom, or the GitHub app/web UI. 

Maybe we can point users to the Kubernetes Style Guide (https://kubernetes.io/docs/contribute/style/content-guide/), which is like a concise version of the Google Style Guide and it's Kubeflow is K8s-based, so it's 👍 . 

So, I suggest we should have: 

1) A step that notifies the users to review their code using the Kubernetes style guide when they open a PR (issue and PR creation can be customized?) 

2) Let the CI/GitHub Actions - e.g. a Markdown linter and a link checker - do the job on the background

---

K8s' [`CONTRIBUTING.md`](https://github.com/kubernetes/website/blob/master/CONTRIBUTING.md) under `/website` has the following paragraph:

```
Before submitting a pull request to create new content, please review the [Kubernetes.io style guide](http://kubernetes.io/docs/home/contribute/style-guide/) and follow the [instructions for using page templates](https://kubernetes.io/docs/contribute/style/page-content-types/).
```

However, I'm not 100% sure all users check `CONTRIBUTING.md` before submitting a PR, especially existing contributors. But having the above-mentioned step is still a nice-to-have.

Kubeflow's site currently has a lengthy contributing section (https://www.kubeflow.org/docs/about/contributing/) and I can't find `CONTRIBUTING.md` on `github.com/kubeflow/website`. Maybe we should have something similar to https://github.com/kubernetes/website/blob/master/CONTRIBUTING.md and include the style guide somewhere in the beginning, since it gets a bit technical with `OWNERS` etc.

cc @RFMVasconcelos @jlewi

**Comment by joeliedtke** [comment]
I'm curious to see if these link checkers work well with our content. It would be great if they could help us prevent the publication of broken links.

To prevent file deletions from breaking links, would it make sense to consider adding a check like the following: "If a file was deleted by this PR, does this PR also include a change to the redirects file?" The thought being that if a file is deleted then we may need a change to the redirects file to prevent links from being broken. This is not necessarily required, since a PR could properly remove all links to a page.

Regarding the style guide, currently Kubeflow has a [style guide](https://www.kubeflow.org/docs/about/style-guide/) that is written at a similar level as the Kubernetes guide. I do tend to refer to the Google style guide in reviews, since it has good illustrations for specific issues that aren't covered directly in the Kubeflow guide. Are there specific changes that we should consider making to the Kubeflow style guide? 

@8bitmp3 , thanks for pointing out the TensorFlow notebook linter. That might be a good starting point for linting for specific terms.

**Comment by Bobgy** [comment]
> I agree but I'm not 100% sure everyone wants to use VS Code as an IDE. Some folks may be editing Markdown using PyCharm, Atom, or the GitHub app/web UI.

I think each of these editors should have similar plugins -- maybe even powered by the same tool -- except GitHub app/web UI. A commandline tool that tells what is wrong will be the fallback if a contributor do not have access to any of those.

**Comment by RFMVasconcelos** [comment]
Love the thought process in this discussion! Standard linting and CI for links both sound fantastic
