### ISSUE TITLE
path of yaml files are not correct

### ISSUE THREAD

**Issue by Subhraj07** [kubeflow/website#2398]
in steps 4 and 5 Path of the .yaml file is not correct. 

The expected path should be 
.cache/manifests/stacks/azure/application/oidc-authservice/kustomization.yaml and
.cache/manifests/istio/oidc-authservice/base/statefulset.yaml

It creates a lot of confusion while searching for the file.

**Comment by 8bitmp3** [comment]
/assign @berndverst @dtzar @eedorenko @sudivate

PTAL (for `manifests/stacks/azure/`)

/assign @krishnadurai @lluunn

PTAL (for `manifests/istio/`)

(@Bobgy @RFMVasconcelos @jlewi - Issue templates that helps with auto-labeling and auto-assigning - a bit like in https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository - should we have that?)

**Comment by Bobgy** [comment]
> (@Bobgy @RFMVasconcelos @jlewi - Issue templates that helps with auto-labeling and auto-assigning - a bit like in https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository - should we have that?)

That's a good idea! Does anyone want to submit a PR for setting it up?

**Comment by berndverst** [comment]
@Subhraj07 That was indeed confusing, as was this GitHub issue.

I made a PR to update the docs. Also thanks for flagging this -- I didn't realize we currently needed to modify files in `.cache`. Not ideal. I'll work with @sudivate to refactor and validate the instructions such that we can add all necessary configuration to the kfctl_azure_aad.v1.2.0.yaml.

By the way, due to some template variables not having been updated automatically the CONFIG URI was still referring to v1.1.0 You may want to verify you installed the version you intended.

For now these instructions should work for you and they should get merged soon:
https://github.com/kubeflow/website/pull/2413

**Comment by Subhraj07** [comment]
Thank you
