### ISSUE TITLE
Add Arrikto EKF distribution

### ISSUE THREAD

**Issue by shannonbradshaw** [kubeflow/website#2639]
Would like to add Arrikto's Enterprise Kubeflow distribution under "docs/Distributions" and in the table of distros on the getting-started/installation page.

**Comment by RFMVasconcelos** [comment]
While Arrikto's effort to push Kubeflow v1.3 out the door deserves a lot of merit, I would like to have a community decision on the topic as it adds a proprietary distribution with no way for a user to try aside from asking for a commercial demo/quote. 

@animeshsingh @aronchick @thesuperzapper @Bobgy any thoughts on this?

**Comment by thesuperzapper** [comment]
There are two points here:

First, I dont really want to add more distribution docs to `kubeflow.org`, as I want to see them move to vendor websites, see issue https://github.com/kubeflow/website/issues/2629.

Second, I dont see any reason not to link them under the "Installing Kubeflow" section for now. But clearly, once we setup a verification process they would be required to undertake the same process as any other distribution. (Whatever verification the governance group of Kubeflow decides to impose)

**Comment by cvenets** [comment]
@RFMVasconcelos I don't see a reason to exclude specifically this distribution, under the generic distributions table.

My understanding is that this was the reason we included the table in the first place, to differentiate from what is official Kubeflow and what isn't. We've put all the relevant warnings, so that users can redirect to distribution owners, if they choose to go with a distribution.

Even if a user goes with a cloud vendor's distro, they actually need a commercial relationship with that vendor to be able to spin up the infrastructure to execute the installation guides. So, it's hard for me to see why this distribution is special.
