### ISSUE TITLE
reference distributions by their names

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2873]
Right now, most distributions are referenced by things other than their "actual names". 

This is confusing for users who aren't actively involved in the community, as they believe the `Kubeflow on XXXX` pages describe the ONLY WAY to deploy Kubeflow on that platform.

Furthermore, as `Kubeflow on AWS` and `Kubeflow on Azure` describe installing `Kubeflow 1.2`, many users mistakenly believe that `Kubeflow 1.3+` is not supported on AWS / Azure.

### Therefore, I propose we reference each distribution like this:

CURRENT | Option 1 | Option 2
--- | --- | ---
Kubeflow on AWS | kfctl - AWS | Kfctl for AWS
Kubeflow on Azure | kfctl - Azure | Kfctl for Azure
Kubeflow on Google Cloud | GCP Blueprints | 
Kubeflow on IBM Cloud | kfctl - IBM Cloud | Kfctl for IBM Cloud
Arrikto Enterprise Kubeflow | _(unchanged)_ | 
Arrikto MiniKF | _(unchanged)_ |
Kubeflow Charmed Operators | Juju Charmed Operators
Kubeflow Operator | kfctl - Operator | Operator for Kfctl
MicroK8s Kubeflow add-on | MicroK8s Add-on |
Kubeflow on OpenShift | kfctl - OpenShift | Kfctl for Openshift

### This would leave us with the following distributions (sorted alphabetically):
NEW
--- |
Arrikto Enterprise Kubeflow |
Arrikto MiniKF |
GCP Blueprints |
Juju Charmed Operators |
Kfctl for AWS |
Kfctl for Azure |
Kfctl for IBM Cloud |
Kfctl for Openshift |
MicroK8s Add-on |
Operator for Kfctl |

**Comment by thesuperzapper** [comment]
@RFMVasconcelos @Bobgy what do you think?

**Comment by johnugeorge** [comment]
My thoughts

Packaged distribution is owned by distribution owner. It doesn't mean that there is only one way to deploy.  
 As given in https://www.kubeflow.org/docs/started/installing-kubeflow/#packaged-distributions,


    There are two pathways to get up and running with Kubeflow, you may either:

     Use a packaged distribution
     Use the manifests (advanced)

 There is always a fallback mechanism to install via manifests. The difference is that deployment via manifests(Option 2) will be supported by community while packaged distribution(Option 1) will be supported by respective owners.

The method of deployment is irrelevant in case of distributions as installers might change for a package. 

And to your question regarding `Kubeflow on AWS support` for `Kubeflow 1.3+`,   I will try `Kubeflow on AWS guide` on `Kubeflow 1.2` as it is not validated for `1.3+`.  `Kubeflow 1.3` might work but distribution owner hasn't validated. So as a user, I will look for other packaged distribution which supports AWS for `1.3+` or use default manifests installation.  Isn't this the whole idea of a packaged distribution for a supported version?

**Comment by thesuperzapper** [comment]
@johnugeorge I think you might be misunderstanding the proposal, the proposal is to __ensure all distributions are referred to by an "actual" name__, rather than something like `Kubeflow on XXX`.

Right now I would argue that `Kubeflow on AWS` is not a valid name for distribution, as it's likely to be confused for an "official" method of deploying Kubeflow on AWS. (Note, the Kubeflow community does not (and will not) provide "official" methods of installation for platforms)

Therefore, because we must rename the `Kubeflow on AWS` distribution to something, an easy option is to name it based on what it does, giving us the name: `kftcl - AWS`

----

However, I think a better option for the kfctl related distributions is actually:

Option 2
--- |
kfctl for AWS |
kfctl for Azure |
kfctl for IBM Cloud |
kfctl for OpenShift |
Operator for kfctl* |

\*this is reversed, as its an Operator \*for\* kfctl

**Comment by thesuperzapper** [comment]
@johnugeorge I think you misunderstand a couple of things:
1. There has never actually been a "distribution" called `Kubeflow on AWS/Azure` that was maintained "officially" by those vendors, they have always lived in the `kubeflow/manifests` repository as [`kfdef` YAML files](https://github.com/kubeflow/manifests/tree/master/distributions/kfdef).  In reality, these "distributions" don't really exist distinct from Kubeflow.
     - When I wrote the "Installing Kubeflow" page I should have asked the vendors to confirm they want to "officially" maintain those distributions, we should probably put the "Maintainer" as "Community" for most of them.
2. These renames __not force OTHER distributions__ to put the tool they use in the name (for example, `Arrikto MiniKF` or `GCP Blueprints` obviously don't include their tools). But going forwards, I __strongly oppose__ adding any more `Kubeflow on XXXX` distributions for the reasons described above:
     - They imply that they are the "official" / "authoritative" method for deploying on that platform (when there are clearly many ways to deploy on all platforms)
     - Being called `Kubeflow on XXXX` is not distinctive enough to help users understand the distinction between a "Distribution of Kubeflow" and "Kubeflow" (similar to how "GKE" is distinct from "Kubernetes")

---

Do you have an alternative proposal for naming `Kubeflow on AWS`? 
If not, I think `Kfctl for AWS` is an easily understandable name.

**Comment by Bobgy** [comment]
I discussed with PSG yesterday, we agree that the problem you are trying to solve is important -- properly guide users on different platforms to choose a **supported** distribution for that platform.

I don't specifically like the new names "Kfctl for AWS", because they expose too much details for users that they cannot understand from the start.

Can we try to solve/mitigate the problem in a few different ways?

Here are our proposals:
* build another table in the getting started page where each row is a platform: "Google Cloud", "AWS", etc, and then list the distributions that are available for the platform. This reduces the cognitive load for understanding that "Conformant Kubernetes" means they can use the specific Kubeflow distribution on any Kubernetes Provider.
* a side note, to ensure distribution quality, I personally believe that the conformance program in https://github.com/kubeflow/community/pull/524 is the way to go. For example, if AWS is not updating their distribution for a while, we can remove "Kubeflow on AWS" from the distribution list because it does not pass latest conformance program.

**Comment by yhwang** [comment]
I guess one of the arguing point is `distribution`. And based on the [wiki](https://en.wikipedia.org/wiki/Software_distribution), it's the process of delivering software to the end user and a collection of components that could be used by end users. For the documents under current `Distributions`, they do serve the purpose of distributions: they point users to a collection of components (the manifest or kfdef files) and configurations to the specific cloud platform. Since the kubeflow is mainly deployed on kubernetes, these documents provide the instructions to use a installer tool (kfctl, kustomize + kubectl and etc) to install a collection of components, configuration on the target cloud platform. And for different cloud provider, these documents also provide configuration/instructions to integrate with their own OIDC provider for login.

I actually don't see any conflicts here.

**Comment by thesuperzapper** [comment]
As discussed in the community meeting today, we can solve the naming issue/confusion by moving "Distributions" that are actually "Guides" to a new section on the website.

That is, we move the distributions which only deploy the `kubeflow/manifests` repo into a new "Guides" section.

Please see the new proposal in issue: https://github.com/kubeflow/website/issues/2967
