### ISSUE TITLE
Design for Multi-user Isolation - Is it up to date? Is it relevant?

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2944]
https://www.kubeflow.org/docs/components/multi-tenancy/design/

**Comment by jbottum** [comment]
@RFMVasconcelos @cvenets @kimwnasptd I think this doc has some good info but it refers to KFAM is depreciated.   Additionally, it uses namespaces, but then refers to workspaces in the next paragraph.   Those might be different constructs but it seems confusing to me.   It also uses identified and validated instead of authN and authZ.   For these reasons, I think it should be removed.
