### ISSUE TITLE
1.4 change should be removed from `v1.3-branch`

### ISSUE THREAD

**Issue by yhwang** [kubeflow/website#3010]
I found my 1.4 change: https://github.com/kubeflow/website/commit/8f005585f9edd99d5de501fe505df4c977048693 is in v1.3-branch. Please help to remove it from `v1.3-branch` or let me know how to do it. Thanks!

**Comment by kimwnasptd** [comment]
@yhwang apologies for this, this happened because we cut the 1.3 branch too late and some PRs that were meant for 1.4 ended up in 1.3 https://github.com/kubeflow/website/issues/2937. To avoid this in the future we will be cutting the docs branch right at the same time we also release, so that everything that gets to master will be going directly for the next release.

Regarding this issue, could you submit a follow-up PR in just in the 1.3 branch to revert the affected files? Again apologies for this inconvenience!

**Comment by yhwang** [comment]
@kimwnasptd no worries. I created a PR: https://github.com/kubeflow/website/pull/3016 to revert my change based on your suggestion.
