### ISSUE TITLE
getting-started.md needs to clarify PV prerequisite

### ISSUE THREAD

**Issue by blsaws** [kubeflow/website#317]
Prior to "Run the following commands to setup and deploy Kubeflow:", the guide needs to clarify that a prerequisite (of vizier-db) is the presence of at least one PV created with no storage class. 
For the Acumos project (https://www.acumos.org/), we have work in progress for our current release to support kubeflow. I am creating kubeflow setup tools and I see that after following the process described by https://www.kubeflow.org/docs/started/getting-started/, that the vizier-db pod is failing to start as it's expecting a PV. This seems to be an oversight in the guide.

I worked aound this issue by adding the following script code prior to '${KUBEFLOW_SRC}/scripts/kfctl.sh init ${KFAPP} --platform none'. NOTE the absence of a storageClassName... this is required since vizier-db's PVC does not reference one:

sudo mkdir /mnt/data
cat <<EOF >pv-volume.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: 
  capacity:
and I see that after following the process at https://www.kubeflow.org/docs/started/getting-started/
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
EOF

  kubectl create -f pv-volume.yaml
  kubectl get pv task-pv-volume

**Comment by jlewi** [comment]
I think the issue here is that Katib is by default relying on the existence of a default storage class.
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1

If your cluster defines a default storage class then it will automatically provision a PV for that PVC.

If your cluster doesn't have a default storage class then the options are

1. Create a PV manually (as in the comment)
1. Disable the use of a PVC and just write to a pod volume

Using a host mounted path in general isn't very robust because pod may be reassigned to a never node.

I think updating the docs to fully describe this would be good improvement.

I'm not sure it makes sense to run Katib without durable storage. That seems like it could cause unexpected failures.

/cc @inc0

**Comment by jlewi** [comment]
@blsaws any interest in providing a PR to update the docs?

**Comment by inc0** [comment]
Alternative approach would be to refactor Katib to use external DB rather than deploying it on it's own. It would be better in general as deploying mysql is hard.

**Comment by CraigSterrett** [comment]
I could take on updating the docs, I ran into this over the weekend on a test cluster that had no default storage class.  Looks like there are 3 PVC's that need to be satisfied.  Not sure where to put it in the doc though, add a brief mention under Requirements, be more verbose and add a section before Download, setup and deploy, or just add a section in Troubleshooting for why the PODs get stuck in pending state?
