### ISSUE TITLE
Broken link - Build a pipeline

### ISSUE THREAD

**Issue by LuigiCerone** [kubeflow/website#3452]
Hello everyone, in the following [page](https://www.kubeflow.org/docs/components/pipelines/v1/sdk-v2/build-pipeline/#understanding-pipelines) the link for `ContainerOp` ([broken link](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html#kfp.dsl.ContainerOp)) is outdated. I think it should point to [this](https://kubeflow-pipelines.readthedocs.io/en/latest/source/dsl.html#kfp.dsl.PipelineTask) link. If my guess is correct, I can open a small PR for it, thanks :)

**Comment by lokesh-sreedhara** [comment]
looks like this issue is fixed 
<img width="987" alt="image" src="https://user-images.githubusercontent.com/110647904/227004353-b23c90b6-be5f-441e-ac27-96f5df56a9fd.png">


the ContainerOp link on https://www.kubeflow.org/docs/components/pipelines/v1/sdk-v2/build-pipeline/#understanding-pipelines seems to be working
