### ISSUE TITLE
Install Kubeflow

### ISSUE THREAD

**Issue by adobemomo** [kubeflow/website#3505]
The link [configuring Kubeflow with kfctl and kustomize](https://www.kubeflow.org/docs/methods/kfctl/kustomize/) is directed to a 404 page

**Comment by thesuperzapper** [comment]
@adobemomo I am confused about what you are asking, but I think you are saying that the Azure docs link to that invalid page. However, the Azure docs are actually really outdated and are being removed in https://github.com/kubeflow/website/pull/3547

If you want to install on Azure, there are a few options, which you can find on the ["Installing Kubeflow"](https://www.kubeflow.org/docs/started/installing-kubeflow/) page.
Personally, I am a fan of [deployKF](https://github.com/deployKF/deployKF) (which I created), but others will work too.

I am gonna close this issue because the azure docs are being removed.
/close
