### ISSUE TITLE
The box 'arrikto/minikf' could not be found or could not be accessed in the remote catalog

### ISSUE THREAD

**Issue by subramankala** [kubeflow/website#653]

**Comment by sarahmaddox** [comment]
/assign @yanniszark 

@yanniszark Please would you take a look at this issue?

**Comment by cspavlou** [comment]
Hi @subramankala,

This seems to be a technical issue. I think that you are trying to download an older version of MiniKF. However, only the latest version of MiniKF is available on Vagrant Cloud, in order to ensure that users get all the latest fixes. We propose to follow the upgrade procedure described in the [MiniKF guide](https://www.kubeflow.org/docs/started/getting-started-minikf/)

Could you please join the [#minikf](https://kubeflow.slack.com/messages/CGRKM3N0G/) channel on [Kubeflow Slack](https://kubeflow.slack.com/join/shared_invite/enQtNDg5MTM4NTQyNjczLWUyZGI1ZmExZWExYWY4YzlkOWI4NjljNjJhZjhjMjEwNGFjNmVkNjg2NTg4M2I0ZTM5NDExZWI5YTIyMzVmNzM), and provide more info on how you ended up with such a message?

**Comment by sarahmaddox** [comment]
Hallo @yanniszark and @subramankala Since this is a tech issue and seems to be not related to the docs, I'll close the issue. Please do open it again if there's doc work required.

/close

**Comment by trackq** [comment]
For anyone experiencing this. Check your vagrant version, maybe it's outdated.
