### ISSUE TITLE
Move katib docs to website

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#72]
Docs were added in kubeflow/kubeflow#989; we should move them to our webiste.

**Comment by amsaha** [comment]
Waiting on #105.

**Comment by sarahmaddox** [comment]
@amsaha @jlewi My 2c is that the Katib docs should be part of "Guides -> Components". Currently the Katib guide is quite short, but we may expand it later so that it becomes more than just a getting-started guide for Katib. 

My thinking is that the "Getting Started" section should focus on getting started with Kubeflow as a whole, rather than on getting started with components of it. So, I think it's OK for the Minikube and gke quickstarts to be in the getting-started section, but the quickstarts for each component belong rather in the "Guides" section.

An added advantage of this thinking is that we can keep the getting-started section short, which makes it simpler for new users.

**Comment by amsaha** [comment]
Thanks @sarahmaddox and @jlewi  for the comments. I will work on this (thats why I assigned it to myself). So I will put it in **Guides->Hyperparameter Tuning**. 

Wondering whether Katib should be part of the name (**Guides->Hyperparameter Tuning (Katib)**) so that users who know of Katib (instead of the general area of hyperparameter tuning) can also easily locate the doc.
