### ISSUE TITLE
Pipelines: Convert an existing TensorFlow tutorial to a pipeline and use prebuilt components

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#737]
Convert an existing TensorFlow tutorial to a pipeline - see some of the new, fun TensorFlow 2.0 tutorials listed below - and where feasible use Kubeflow Pipelines reusable components in the pipeline. 

Notes:

* We'll probably need to develop one or more reusable components as well as building the tutorial, to fill any gaps in our current supply of reusable components.
* These are the “hot” areas of AI. All using TF 2.0 - Keras. There may be some challenges using them. Part of the task during the doc sprint will be to overcome the challenges and document the way in which we did that.
* It's probably best to avoid workflows that require TPUs.
* We need to check the TF tutorials listed below to see if they’re good use cases for a pipeline. During the doc sprint or as prework, break them into steps and decide which can be created as reusable pipelines. 
* Some of the TF tutorials pull in TensorFlow Hub modules.

TensorFlow tutorials to consider for conversion to a pipeline:

* [Neural Machine Translation with Attention](https://www.tensorflow.org/alpha/tutorials/text/nmt_with_attention)

* [Pix2Pix](https://www.tensorflow.org/alpha/tutorials/generative/pix2pix)

* [Transformer model for language understanding](https://www.tensorflow.org/alpha/tutorials/text/transformer)

* [Image Captioning with Attention](https://www.tensorflow.org/alpha/tutorials/text/image_captioning)

* [Convolutional Variational Autoencoder](https://www.tensorflow.org/alpha/tutorials/generative/cvae)

* [Deep Convolutional Generative Adversarial Network](https://www.tensorflow.org/alpha/tutorials/generative/dcgan)

* [Neural style transfer](https://www.tensorflow.org/alpha/tutorials/generative/style_transfer)

**Comment by sarahmaddox** [comment]
@zanedurante is interested in working on the "Neural style transfer" tutorial during the doc sprint.

**Comment by fdasilva59** [comment]
Hi @sarahmaddox I am checking this issue regarding the KF doc sprint that's about to start :)

I am using KF 0.5 on GKE, and I have previously implemented a demo of [Pix2Pix with TF1.12 on KF/GKE](https://github.com/fdasilva59/Pix2Pix-Kubeflow-Demo). 

My pipeline is composed of 3 tasks : download dataset, prepare dataset (create TFRecord from the pictures), and train pix2pix (use a tf.data pipeline to prepare/do data augmentation to the pictures + build and train a conditional GAN). My pipelines uses a GPU for the training task and use NFS volumes to access the pictures/TFRecord file, and outputs the generated image. It also generate Tensorboard logs on GS.

FYI, I couldn't use at that time TF1.13 or above because only CUDA 9 was available on GKE. But it looks like the [GCP documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus?hl=en#cuda) has been updated late June, and that CUDA 10 is now available. I will verify right now,  if it works with TF 1.13 and GPU. If ok, I might be able to contribute on that one if a Pix2Pix with TF2.0 is chosen for the doc sprint

**Comment by sarahmaddox** [comment]
Thanks @fdasilva59 that sounds great. I've created an issue to track your work:
https://github.com/kubeflow/website/issues/876

**Comment by sarahmaddox** [comment]
I'm going to close this issue, as we've branched off a couple of specific TF models into separate issues, and this one is to broad to track work.

/close
