### ISSUE TITLE
Pipelines: Convert the TF "Image Captioning with Attention" tutorial to a pipeline

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#822]
Convert the TensorFlow [Image Captioning with Attention](https://www.tensorflow.org/beta/tutorials/text/image_captioning) tutorial to a pipeline and where feasible use Kubeflow Pipelines reusable components in the pipeline.

**Comment by sarahmaddox** [comment]
@zanedurante will work on this tutorial as part of the Kubeflow Doc Sprint

/doc-sprint

**Comment by zanedurante** [comment]
@sarahmaddox Since I was already working on this project with the pipelines team, the pipeline was merged [here](https://github.com/kubeflow/pipelines/tree/master/samples/notebooks/image-captioning-gcp) in the pipelines samples repo (instead of `kubeflow/examples`). 

PR here: https://github.com/kubeflow/pipelines/pull/1591
