### ISSUE TITLE
Remove ksonnet references from deployment pages

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/website#864]
GKE: https://www.kubeflow.org/docs/gke/deploy/deploy-cli/
Azure: https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/
AWS: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

All 3 are currently still referencing ksonnet.

**Comment by scottilee** [comment]
@sarahmaddox Can I get a confirmation that kubeflow no longer has any dependencies on ksonnet? The reason I am asking is that a few weeks ago I ran into an issue installing kubeflow on Minikube and the fix was to bump the version of ksonnet (https://github.com/kubeflow/kubeflow/issues/3410).

Once I get the confirmation I can remove references to ksonnet from the GKE, Azure, and AWS pages.

**Comment by sarahmaddox** [comment]
@richardsliu Can you answer @scottilee's question?

**Comment by richardsliu** [comment]
@scottilee Yes we no longer depend on ksonnet in the latest release. I will work on updating the gke instructions, can you help with AWS and Azure?

**Comment by scottilee** [comment]
@richardsliu Yes, I will try to finish it by tonight.

**Comment by sarahmaddox** [comment]
Related issue: https://github.com/kubeflow/website/issues/867

**Comment by sarahmaddox** [comment]
/assign @richardsliu 
/assign @scottilee 

Thanks both!

**Comment by scottilee** [comment]
Pull request is up: https://github.com/kubeflow/website/pull/911

**Comment by scottilee** [comment]
The pull request was merged, thanks @sarahmaddox and @richardsliu!

**Comment by richardsliu** [comment]
Thanks @scottilee for your contribution!
