### ISSUE TITLE
Improve Sidebar Style

### ISSUE THREAD

**Issue by Daniel-Sanche** [kubeflow/website#894]
I find the sidebar on the Kubeflow docs page difficult to read. font weights are used both to distinguish folders from files, and to highlight the selected page. Additionally, indents are small, so it's hard to determine the page heirarchy

We inheritted these issues from the [docsy theme](https://github.com/google/docsy), but it looks like we can make local downstream changes to the theme [using this method.](https://bwaycer.github.io/hugo_tutorial.hugo/themes/customizing/)

I attempted to improve the sidebar on a [branch here](https://github.com/DanSanche/website/blob/style-sidebar/assets/scss/_sidebar-tree.scss), but I'm not much of a front end person, so I'm sure someone else can do better. Any takers?

Current sidebar:
<img width="288" alt="Screen Shot 2019-07-10 at 8 16 53 PM" src="https://user-images.githubusercontent.com/3914119/61019775-41503f00-a350-11e9-888c-aace87da5092.png">

My update attempt:
<img width="286" alt="Screen Shot 2019-07-10 at 8 17 00 PM" src="https://user-images.githubusercontent.com/3914119/61019768-372e4080-a350-11e9-9b8c-f430da9c5e3a.png">

**Comment by DanSanche** [comment]
👍

**Comment by kbhawkey** [comment]
I agree that the left nav item text is bold and non-bold at times. The contrasting text does not help navigation. For instance, if I select `Pipelines`, this header item is _strong_ bold; the first item, `Pipelines Quickstart` is regular text, the next two items are medium bold, the next item `Upgrading and Reinstalling` is regular text, and the last two items are medium bold. I think eliminating the medium bold on the non-selected text would help the navigation.

**Comment by alecglassford** [comment]
Haven't had a chance to dive deep into this but my initial reactions:

1. The increased indentation is big improvement! Have you checked that it shows up alright on mobile devices / small screens?

2. Your example has opted not to use bolding at all, right? I do think this is less confusing (the example @kbhawkey is quite confusing due to the nested bolding). However, in your screenshot it becomes a bit hard to see which items are "leaf" pages and which have other ones nested underneath them. I believe your schema is
  * "white bullet" = ancestor of current page (uncollapsed parent)
  * "black bullet" = parent of other pages (collapsed parent)
  * no bullet = "leaf" page
  * (highlighted blue = current page)

I think you could clarify this schema by using something like
  * "▾" = parent of current page (uncollapsed parent)
  * "▸" = parent of other pages (collapsed parent)
  * no bullet = "leaf" page
  * (highlighted blue *and* bold = current page) --> I'm not sure this will look good, but it may make it *slightly* more prominent to readers with some visual impairment and also distinguish it from the blue that happens when you mouseover unselected pages in the leftnav

What do you think? See the collapsed/uncollapsed triangles in the left-nav of https://cloud.google.com/ml-engine/docs/ for a somewhat analagous design. (To be clear, I'm not sure that these exact triangle Unicode characters are the best choices, but I don't think kubeflow.org has an icon library so they're probably the easiest choice 😄)

**Comment by DanSanche** [comment]
I agree that the triangles would be a better option, but there is an issue: Users expect to be able to click on a triangle to collapse or expand a section, but here they only work to expand a section, not collapse. I had a prototype with triangles, but I found myself trying to click to collapse and getting disappointed when it didn't work

I did open an [issue in docsy](https://github.com/google/docsy/issues/100) to add true collapsible sections, and it seems like they're working on them, so that would help a lot
