### ISSUE TITLE
Set Up Your Notebooks

### ISSUE THREAD

**Issue by batigooal** [kubeflow/website#912]
https://www.kubeflow.org/docs/notebooks/setup/

there is not any response when the button "+ new server" is clicked

**Comment by sarahmaddox** [comment]
Hallo @batigooal I've just installed Kubeflow v0.7.0 RC5, and managed to successfully create a notebook server. I think this issue may have been a temporary issue, perhaps caused by a specific environment.

If the problem occurs again, please would you open an issue in the [kubeflow/kubeflow](https://github.com/kubeflow/kubeflow/issues) issue tracker, as the problem doesn't seem to be related to the docs.

/close
