### ISSUE TITLE
ksonnet-to-kustomize migration: Add a note to component docs that are not yet converted

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#989]
Add a note to the component docs for components that are not yet converted to kustomize or documented. In the note, link to the issue tracking the conversion: https://github.com/kubeflow/manifests/issues/176

**Comment by sarahmaddox** [comment]
@scottilee is this something you could take on? Basically, we need to check all the components in this section that are not yet converted to kustomize:
https://www.kubeflow.org/docs/components/

And map them to the comments and related issues mentioned on this issue:
https://github.com/kubeflow/manifests/issues/176

Then add a note to the doc for each affected component, saying that the component does not yet have a kustomize manifest and linking to the relevant issue.

**Comment by scottilee** [comment]
@sarahmaddox Sure, will take a look.

/assign

**Comment by scottilee** [comment]
@sarahmaddox I don't see an issue for https://www.kubeflow.org/docs/components/serving/tfbatchpredict/ or https://www.kubeflow.org/docs/components/training/pytorch/. Otherwise my pull request covers the rest although I was unsure about https://www.kubeflow.org/docs/components/serving/pytorchserving/ since it also didn't have an explicit issue but it seemed related to Seldon so I added that issue.
